# Generated by Django 6.0.3 on 2026-04-03 09:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="ATUL INDUSTRIES", max_length=255)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pin", models.CharField(blank=True, max_length=20, null=True)),
                ("gstin", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("bank", models.CharField(blank=True, max_length=255, null=True)),
                ("account", models.CharField(blank=True, max_length=100, null=True)),
                ("ifsc", models.CharField(blank=True, max_length=50, null=True)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                ("defaultTerms", models.TextField(blank=True, null=True)),
                ("pipePacking", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="MasterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("gstin", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("pin", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=255, unique=True)),
                ("rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Salesperson",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("validTill", models.DateField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("discount", models.FloatField(default=0)),
                ("showDiscInPDF", models.BooleanField(default=False)),
                ("freight", models.FloatField(default=0)),
                ("subtotal", models.FloatField(default=0)),
                ("gstAmt", models.FloatField(default=0)),
                ("grandTotal", models.FloatField(default=0)),
                ("shipTo", models.JSONField(blank=True, null=True)),
                (
                    "partyId",
                    models.ForeignKey(
                        db_column="partyId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proformas",
                        to="invoices.party",
                    ),
                ),
                (
                    "spId",
                    models.ForeignKey(
                        db_column="spId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proformas",
                        to="invoices.salesperson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("itemName", models.CharField(max_length=255)),
                ("qty", models.FloatField()),
                ("rate", models.FloatField()),
                ("listRate", models.FloatField()),
                ("netRate", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
                ("disc", models.FloatField(default=0)),
                ("itemDisc", models.FloatField(default=0)),
                ("narration", models.CharField(blank=True, max_length=255, null=True)),
                ("manualNet", models.FloatField(blank=True, null=True)),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.proformainvoice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="party",
            name="spId",
            field=models.ForeignKey(
                db_column="spId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="invoices.salesperson",
            ),
        ),
    ]
